import { Artist, BlogPost, AddOnOption, MehndiCategory } from '@/types/mehndi';

export const MEHNDI_CATEGORIES: {
  id: MehndiCategory;
  name: string;
  tagline: string;
  description: string;
  imageUrl: string;
  count: number;
}[] = [
  {
    id: 'Bridal',
    name: 'Royal Bridal Heirloom',
    tagline: 'Intricate storytelling, portraits & symmetrical motifs',
    description: 'Dense, regal bridal henna spanning fingertips to elbows with custom couple portraits, elephant motifs, and personalized wedding vows.',
    imageUrl: 'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?auto=format&fit=crop&w=800&q=80',
    count: 240,
  },
  {
    id: 'Arabic',
    name: 'Contemporary Arabic',
    tagline: 'Flowing floral trails, bold negative space & modern elegance',
    description: 'Distinct bold outlines, shaded leafy vines, geometric bel patterns, and open skin spaces that create striking, chic contrast.',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    count: 185,
  },
  {
    id: 'Rajasthani & Traditional',
    name: 'Rajasthani & Traditional',
    tagline: 'Timeless Marwari jaal, peacocks & heritage motifs',
    description: 'Authentic heritage patterns with ultra-fine jaali (mesh) work, royal jharokhas, dancing peacocks, and traditional dholak elements.',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    count: 160,
  },
  {
    id: 'Indo-Western & Modern',
    name: 'Indo-Western Fusion',
    tagline: 'Architectural lines, Moroccan geometries & lace cuffs',
    description: 'Clean modern lace patterns, mandala cuffs, abstract floral geometry, and glove-inspired silhouettes favored for cocktail nights.',
    imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
    count: 130,
  },
  {
    id: 'Minimalist Mandala',
    name: 'Minimalist & Mandala',
    tagline: 'Delicate central mandalas & refined finger accents',
    description: 'Understated luxury for minimal brides, bridesmaids, and modern festive wear with fine jewel-drop chains and focal circular mandalas.',
    imageUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
    count: 110,
  },
  {
    id: 'Festive & Eid',
    name: 'Festive, Eid & Sangeet',
    tagline: 'Quick-drying party henna for celebrations & guests',
    description: 'Vibrant, fast-setting designs tailored for sangeet guests, Eid celebrations, Karwa Chauth, and family parties.',
    imageUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
    count: 195,
  },
];

export const STANDARD_ADDONS: AddOnOption[] = [
  {
    id: 'feet_bridal',
    title: 'Full Bridal Feet Henna (To Mid-Calf)',
    description: 'Symmetrical intricate bridal feet patterns matching your hand design up to the mid-calf.',
    price: 180,
    durationMinutes: 90,
  },
  {
    id: 'feet_minimal',
    title: 'Anklet & Minimal Feet Accents',
    description: 'Graceful floral payal anklet design with ornate toe accents.',
    price: 85,
    durationMinutes: 45,
  },
  {
    id: 'groom_henna',
    title: 'Groom Royal Minimal Henna',
    description: 'Subtle mandala or customized bride initials / hashtag emblem on groom palm.',
    price: 65,
    durationMinutes: 30,
  },
  {
    id: 'organic_aftercare_kit',
    title: 'VIP Organic Henna Aftercare & Balm Kit',
    description: 'Includes pure essential clove oil infusion, natural beeswax balm, and breathable mehendi sealant wrap.',
    price: 35,
    durationMinutes: 0,
  },
  {
    id: 'extra_party_hands',
    title: 'Bridesmaids & Family Henna (Pack of 3)',
    description: 'Side-by-side speed henna application for 3 loved ones (palms & fingers).',
    price: 140,
    durationMinutes: 60,
  },
];

export const MOCK_ARTISTS: Artist[] = [
  {
    id: 'artist-ayesha-khan',
    name: 'Ayesha Noor Khan',
    handle: '@ayeshanoor_henna',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?auto=format&fit=crop&w=1200&q=80',
    title: 'Celebrity Bridal Henna Couturier',
    bio: 'Pioneering heirloom bridal mehndi with 100% triple-filtered organic Rajasthani henna. Featured in Vogue Weddings & Harper’s Bazaar Bride.',
    story: 'Trained under third-generation master artisans in Udaipur and Lahore, Ayesha blends royal Mughal architectural motifs with fine-line precision that develops into a rich mahogany mahogany stain.',
    city: 'Dubai',
    state: 'Downtown & Palm Jumeirah',
    country: 'United Arab Emirates',
    rating: 4.98,
    reviewCount: 142,
    experienceYears: 9,
    startingPrice: 350,
    currency: 'USD',
    verified: true,
    featured: true,
    proMember: true,
    responseTimeMinutes: 15,
    minAdvanceBookingDays: 14,
    travelsToVenue: true,
    organicChemicalFreeGuarantee: true,
    badges: ['Top Celebrity Pick 2026', 'Master Artisan', '100% Organic Certified'],
    specialties: ['Bridal', 'Arabic', 'Rajasthani & Traditional'],
    socialLinks: {
      instagram: 'https://instagram.com',
      youtube: 'https://youtube.com',
      whatsapp: '+971501234567',
      website: 'https://ayeshanoorhenna.com',
    },
    stats: {
      completedWeddings: 320,
      bridesServed: 480,
      repeatClientsPercent: 94,
    },
    packages: [
      {
        id: 'ayesha-pkg-1',
        artistId: 'artist-ayesha-khan',
        title: 'Heirloom Royal Bridal Signature',
        tier: 'bridal_royal',
        price: 650,
        originalPrice: 750,
        durationMinutes: 240,
        handsDescription: 'Full arms up to elbows, intricate front & back with personalized portraiture & wedding date hidden motifs.',
        feetIncluded: true,
        organicCones: true,
        touchupKit: true,
        popular: true,
        description: 'Our flagship bridal experience. Pure organic Rajasthani triple-sifted henna, custom bride-groom motifs, and full feet coverage.',
        inclusions: [
          'Full arms to elbows (Front & Back intricate Jaal)',
          'Complete bridal feet henna up to mid-calf',
          'Custom couple portraits & hidden initials game',
          'Premium eucalyptus & tea tree organic cones',
          'VIP sealant spray & beeswax stain booster kit',
          'Complimentary touch-up for 2 bridesmaids',
        ],
      },
      {
        id: 'ayesha-pkg-2',
        artistId: 'artist-ayesha-khan',
        title: 'Modern Luxe Bridal Silver',
        tier: 'bridal_silver',
        price: 450,
        durationMinutes: 180,
        handsDescription: 'Forearms to wrists, front & back intricate contemporary Arabic fusion.',
        feetIncluded: true,
        organicCones: true,
        touchupKit: true,
        description: 'A lighter contemporary look combining bold Arabic floral trails with fine mandala elements.',
        inclusions: [
          'Forearms to fingertips (Front & Back)',
          'Bridal feet anklet & toe mandalas',
          'Organic natural henna cones',
          'Aftercare sealant kit with organic balm',
        ],
      },
      {
        id: 'ayesha-pkg-3',
        artistId: 'artist-ayesha-khan',
        title: 'Engagement & Sangeet Solo Pack',
        tier: 'engagement',
        price: 260,
        durationMinutes: 90,
        handsDescription: 'Palms and delicate backhand glove cuffs.',
        feetIncluded: false,
        organicCones: true,
        touchupKit: false,
        description: 'Ideal for engagement ceremonies, intimate sangeet nights, or festive celebrations.',
        inclusions: [
          'Palms and backhands with modern cuffs',
          'Triple-sifted organic henna cones',
          'Natural clove oil infusion',
        ],
      },
    ],
    portfolio: [
      {
        id: 'port-ay-1',
        title: 'Royal Udaipur Symmetrical Jaal',
        category: 'Bridal',
        imageUrl: 'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?auto=format&fit=crop&w=800&q=80',
        stainedImageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        description: 'Full bridal sleeve featuring delicate jali mesh, lotus bud bands, and mirrored peacock mandalas.',
        likesCount: 1420,
        featured: true,
        handType: 'Bridal Full Set',
      },
      {
        id: 'port-ay-2',
        title: 'Contemporary Gulf Shaded Florals',
        category: 'Arabic',
        imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
        description: 'Free-flowing diagonal vine with shaded petals and negative-space cutouts.',
        likesCount: 980,
        featured: true,
        handType: 'Backhand',
      },
      {
        id: 'port-ay-3',
        title: 'Regal Payal Foot Cascade',
        category: 'Bridal',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        description: 'Bridal feet henna adorned with heritage anklet strings and fine lattice work.',
        likesCount: 1150,
        featured: false,
        handType: 'Feet',
      },
      {
        id: 'port-ay-4',
        title: 'Minimalist Concentric Sun Mandala',
        category: 'Minimalist Mandala',
        imageUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
        description: 'Crisp concentric circles with delicate jewel chains draping toward the wrist.',
        likesCount: 760,
        featured: false,
        handType: 'Palm',
      },
    ],
    reviews: [
      {
        id: 'rev-ay-1',
        artistId: 'artist-ayesha-khan',
        customerName: 'Samira Al-Maktoum',
        customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        customerCity: 'Dubai',
        rating: 5,
        date: '3 days ago',
        eventType: 'Wedding / Bridal',
        comment: 'Ayesha was pure magic! Her hands work with such fluid grace, and the stain on my wedding day was the deepest, most gorgeous rich mahogany. All our international guests were in awe.',
        verifiedBride: true,
        photos: [
          'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?auto=format&fit=crop&w=600&q=80',
        ],
        artistReply: {
          comment: 'Dearest Samira, you were the most radiant bride! Wishing you a lifetime of joy and blessings.',
          date: '2 days ago',
        },
      },
      {
        id: 'rev-ay-2',
        artistId: 'artist-ayesha-khan',
        customerName: 'Zara Siddiqui',
        customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
        customerCity: 'London & Dubai',
        rating: 5,
        date: '2 weeks ago',
        eventType: 'Wedding / Bridal',
        comment: 'Unbelievable precision! The hidden initials game had my groom searching for 20 minutes during the ceremony. The organic kit she provided gave zero chemical irritation.',
        verifiedBride: true,
      },
    ],
    availability: [
      {
        date: '2026-09-02',
        slots: [
          { time: '10:00 AM', available: true },
          { time: '02:30 PM', available: false, bookedBy: 'Reema H.' },
          { time: '06:30 PM', available: true },
        ],
      },
      {
        date: '2026-09-03',
        slots: [
          { time: '11:00 AM', available: true },
          { time: '04:00 PM', available: true },
        ],
      },
    ],
  },
  {
    id: 'artist-priya-sharma',
    name: 'Priya Sharma',
    handle: '@priyamehendi_art',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80',
    title: 'Heritage Rajasthani & Marwari Master',
    bio: '12 years of fine Marwari artistry specializing in royal wedding baraat scenes, Radha-Krishna storytelling motifs, and mirror-symmetrical bridal art.',
    story: 'Preserving authentic Rajasthani heritage through micro-lines and handmade organic Sojat henna paste prepared fresh before every booking.',
    city: 'New Delhi',
    state: 'South Delhi & NCR',
    country: 'India',
    rating: 4.96,
    reviewCount: 198,
    experienceYears: 12,
    startingPrice: 280,
    currency: 'USD',
    verified: true,
    featured: true,
    proMember: true,
    responseTimeMinutes: 20,
    minAdvanceBookingDays: 20,
    travelsToVenue: true,
    organicChemicalFreeGuarantee: true,
    badges: ['Vogue Top 10 Delhi', 'Organic Sojat Certified', 'Destination Wedding Specialist'],
    specialties: ['Rajasthani & Traditional', 'Bridal', 'Minimalist Mandala'],
    socialLinks: {
      instagram: 'https://instagram.com',
      youtube: 'https://youtube.com',
      whatsapp: '+919811223344',
    },
    stats: {
      completedWeddings: 510,
      bridesServed: 740,
      repeatClientsPercent: 96,
    },
    packages: [
      {
        id: 'priya-pkg-1',
        artistId: 'artist-priya-sharma',
        title: 'Royal Marwari Heirloom Bridal',
        tier: 'bridal_royal',
        price: 520,
        originalPrice: 600,
        durationMinutes: 270,
        handsDescription: 'Full arms past elbows with Doli, Shehnai, elephant processions, and couple portraits.',
        feetIncluded: true,
        organicCones: true,
        touchupKit: true,
        popular: true,
        description: 'Complete royal Rajasthani bridal experience crafted with traditional organic Sojat henna.',
        inclusions: [
          'Full arms above elbows with royal procession motifs',
          'Bridal feet to mid-calf with authentic Marwari Jaali',
          'Organic Sojat fresh cone preparation with essential oils',
          'Bridal aftercare sealant & clove steam guide',
        ],
      },
      {
        id: 'priya-pkg-2',
        artistId: 'artist-priya-sharma',
        title: 'Classic Sangeet Bridal Pack',
        tier: 'bridal_silver',
        price: 360,
        durationMinutes: 180,
        handsDescription: 'Forearms to fingertips with peacock and lotus motifs.',
        feetIncluded: true,
        organicCones: true,
        touchupKit: true,
        description: 'Classic heritage motifs focused on elegance and comfort.',
        inclusions: [
          'Forearms to fingertips (Front & Back)',
          'Feet up to ankles with floral cuffs',
          'Pure organic cone set',
        ],
      },
    ],
    portfolio: [
      {
        id: 'port-pr-1',
        title: 'Baraat & Doli Storyline Bridal',
        category: 'Rajasthani & Traditional',
        imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        description: 'Storyline bridal henna detailing the royal wedding journey from engagement to varmala.',
        likesCount: 2100,
        featured: true,
        handType: 'Bridal Full Set',
      },
    ],
    reviews: [
      {
        id: 'rev-pr-1',
        artistId: 'artist-priya-sharma',
        customerName: 'Ananya Malhotra',
        customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        customerCity: 'New Delhi',
        rating: 5,
        date: '1 week ago',
        eventType: 'Wedding / Bridal',
        comment: 'Priya did the mehendi for both me and my sister. Her symmetrical jaal is literally computer-like in precision! The organic balm left our hands smelling like sweet cloves.',
        verifiedBride: true,
      },
    ],
    availability: [
      {
        date: '2026-09-04',
        slots: [
          { time: '10:00 AM', available: true },
          { time: '03:00 PM', available: true },
        ],
      },
    ],
  },
  {
    id: 'artist-fatima-zahra',
    name: 'Fatima Al-Zahra',
    handle: '@fatima_gulfhenna',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80',
    title: 'Modern Khaleeji & Arabic Henna Stylist',
    bio: 'Crafting ultra-modern Gulf, Moroccan, and Dubai couture henna. Famous for clean negative space, bold shade transitions, and lace-glove designs.',
    story: 'Fatima redefined Gulf bridal style with minimalist silhouettes, shaded rose petals, and jewelry-inspired cuffs that complement diamond and polki jewelry.',
    city: 'London',
    state: 'Mayfair & Kensington',
    country: 'United Kingdom',
    rating: 4.97,
    reviewCount: 114,
    experienceYears: 8,
    startingPrice: 320,
    currency: 'USD',
    verified: true,
    featured: true,
    proMember: true,
    responseTimeMinutes: 10,
    minAdvanceBookingDays: 10,
    travelsToVenue: true,
    organicChemicalFreeGuarantee: true,
    badges: ['UK Asian Wedding Winner', 'Arabic Couture Specialist', 'Natural Henna Certified'],
    specialties: ['Arabic', 'Indo-Western & Modern', 'Minimalist Mandala'],
    socialLinks: {
      instagram: 'https://instagram.com',
      whatsapp: '+447911123456',
    },
    stats: {
      completedWeddings: 260,
      bridesServed: 390,
      repeatClientsPercent: 92,
    },
    packages: [
      {
        id: 'fatima-pkg-1',
        artistId: 'artist-fatima-zahra',
        title: 'Khaleeji Royal Arabic Bridal',
        tier: 'bridal_royal',
        price: 580,
        originalPrice: 650,
        durationMinutes: 200,
        handsDescription: 'Full forearms with bold shaded roses, flowing vines, and Moroccan lace cuffs.',
        feetIncluded: true,
        organicCones: true,
        touchupKit: true,
        popular: true,
        description: 'The pinnacle of modern Arabic bridal chic.',
        inclusions: [
          'Forearms to fingers with high-contrast shaded Arabic florals',
          'Matching Moroccan lace feet accents',
          'Organic certified fresh henna cones',
          'Gold foil seal wrapping for maximum dark stain',
        ],
      },
    ],
    portfolio: [
      {
        id: 'port-fz-1',
        title: 'Moroccan Lace & Shaded Bloom',
        category: 'Arabic',
        imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
        description: 'Negative space masterpiece with deep shaded floral leaves.',
        likesCount: 1640,
        featured: true,
      },
    ],
    reviews: [
      {
        id: 'rev-fz-1',
        artistId: 'artist-fatima-zahra',
        customerName: 'Layla Crawford',
        customerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
        customerCity: 'London',
        rating: 5,
        date: '5 days ago',
        eventType: 'Wedding / Bridal',
        comment: 'Fatima flew down to our Cotswolds wedding venue. Everyone was obsessed with how clean and modern my henna was!',
        verifiedBride: true,
      },
    ],
    availability: [
      {
        date: '2026-09-05',
        slots: [
          { time: '11:00 AM', available: true },
          { time: '04:00 PM', available: true },
        ],
      },
    ],
  },
  {
    id: 'artist-zainab-mirza',
    name: 'Zainab Mirza',
    handle: '@zainab_henna_couture',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    title: 'Mughal Architecture & Floral Specialist',
    bio: 'Known for ultra-fine symmetry inspired by Lahore Badshahi Mosque jaali and Persian garden florals. 100% natural essential oil cones.',
    story: 'Zainab brings 10 years of bridal mastery, celebrated across Lahore and Karachi for delicate mesh jaal that looks like spun lace on silk.',
    city: 'Lahore',
    state: 'Gulberg & DHA',
    country: 'Pakistan',
    rating: 4.99,
    reviewCount: 220,
    experienceYears: 10,
    startingPrice: 240,
    currency: 'USD',
    verified: true,
    featured: true,
    proMember: true,
    responseTimeMinutes: 12,
    minAdvanceBookingDays: 14,
    travelsToVenue: true,
    organicChemicalFreeGuarantee: true,
    badges: ['Bride’s Choice 2026', 'Ultra Fine Line Specialist', 'Celebrity Preferred'],
    specialties: ['Bridal', 'Rajasthani & Traditional', 'Festive & Eid'],
    socialLinks: {
      instagram: 'https://instagram.com',
      whatsapp: '+923001234567',
    },
    stats: {
      completedWeddings: 440,
      bridesServed: 680,
      repeatClientsPercent: 95,
    },
    packages: [
      {
        id: 'zm-pkg-1',
        artistId: 'artist-zainab-mirza',
        title: 'Shahi Mughal Bridal Heirloom',
        tier: 'bridal_royal',
        price: 480,
        durationMinutes: 240,
        handsDescription: 'Elbow-length Mughal jharokhas, mirrored jaal, and bespoke bridal vows.',
        feetIncluded: true,
        organicCones: true,
        touchupKit: true,
        popular: true,
        description: 'Regal bridal package with custom miniature arches and shaded lotuses.',
        inclusions: [
          'Full arms to elbows (Front & Back)',
          'Elaborate bridal feet to mid-calf',
          'Triple sifted organic Sojat paste with lavender oil',
          'Bridal aftercare gift box with essential clove butter',
        ],
      },
    ],
    portfolio: [
      {
        id: 'port-zm-1',
        title: 'Badshahi Archway Bridal Set',
        category: 'Bridal',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        description: 'Mughal arched frames housing micro lotus and delicate floral vine fillings.',
        likesCount: 1890,
        featured: true,
      },
    ],
    reviews: [
      {
        id: 'rev-zm-1',
        artistId: 'artist-zainab-mirza',
        customerName: 'Mahnoor Tariq',
        customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        customerCity: 'Lahore',
        rating: 5,
        date: '4 days ago',
        eventType: 'Wedding / Bridal',
        comment: 'Zainab is simply the best in Pakistan. The intricate jharokha design she drew made my bridal look unforgettable.',
        verifiedBride: true,
      },
    ],
    availability: [
      {
        date: '2026-09-06',
        slots: [
          { time: '10:00 AM', available: true },
          { time: '02:00 PM', available: true },
        ],
      },
    ],
  },
  {
    id: 'artist-meera-kapoor',
    name: 'Meera Kapoor',
    handle: '@meera_henna_studio',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80',
    title: 'Indo-Western & Geometric Fusion Artist',
    bio: 'Bridging heritage henna with runway fashion aesthetics. Specializing in minimalist jewelry mandalas, glove cuffs, and festival chic.',
    story: 'Meera has designed henna for New York Fashion Week and high-profile fusion weddings across Manhattan, Toronto, and Mumbai.',
    city: 'New York',
    state: 'Manhattan & Brooklyn',
    country: 'United States',
    rating: 4.95,
    reviewCount: 96,
    experienceYears: 7,
    startingPrice: 300,
    currency: 'USD',
    verified: true,
    featured: false,
    proMember: true,
    responseTimeMinutes: 18,
    minAdvanceBookingDays: 7,
    travelsToVenue: true,
    organicChemicalFreeGuarantee: true,
    badges: ['NYFW Featured Artist', '100% Organic Henna', 'Modern Fusion Specialist'],
    specialties: ['Indo-Western & Modern', 'Minimalist Mandala', 'Arabic'],
    socialLinks: {
      instagram: 'https://instagram.com',
      website: 'https://meerahennanyc.com',
    },
    stats: {
      completedWeddings: 180,
      bridesServed: 290,
      repeatClientsPercent: 91,
    },
    packages: [
      {
        id: 'meera-pkg-1',
        artistId: 'artist-meera-kapoor',
        title: 'Tribeca Modern Fusion Bridal',
        tier: 'bridal_silver',
        price: 490,
        durationMinutes: 180,
        handsDescription: 'Forearms with intricate geometric lace and delicate glove mandalas.',
        feetIncluded: true,
        organicCones: true,
        touchupKit: true,
        popular: true,
        description: 'Chic, modern bridal styling tailored for contemporary western gowns and lehengas.',
        inclusions: [
          'Forearm lace cuffs and mandala palms',
          'Minimal chic foot anklet details',
          'Organic natural henna cones with cajeput oil',
          'Sealant spray & aftercare instructions',
        ],
      },
    ],
    portfolio: [
      {
        id: 'port-mk-1',
        title: 'Geometrical Lace Cuff with Jewel Drapes',
        category: 'Indo-Western & Modern',
        imageUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
        description: 'Sleek architectural cuff with delicate cascading beadlines.',
        likesCount: 890,
        featured: true,
      },
    ],
    reviews: [
      {
        id: 'rev-mk-1',
        artistId: 'artist-meera-kapoor',
        customerName: 'Chloe Bennett',
        customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
        customerCity: 'New York',
        rating: 5,
        date: '2 weeks ago',
        eventType: 'Wedding / Bridal',
        comment: 'Meera created an unbelievable fusion design that matched both my white wedding dress and my reception saree. 10/10 recommended!',
        verifiedBride: true,
      },
    ],
    availability: [
      {
        date: '2026-09-07',
        slots: [
          { time: '01:00 PM', available: true },
          { time: '05:30 PM', available: true },
        ],
      },
    ],
  },
  {
    id: 'artist-ritika-patel',
    name: 'Ritika Patel',
    handle: '@ritika_bridalmehendi',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?auto=format&fit=crop&w=1200&q=80',
    title: 'Bridal Portraiture & Storytelling Artist',
    bio: 'Specialist in custom couple portraits, pet illustrations in henna, and personalized wedding skyline designs. 8+ years experience.',
    story: 'Ritika turns bridal henna into personal wedding albums, drawing high-detail portraits of the couple, proposal moments, and family crests.',
    city: 'Mumbai',
    state: 'Bandra & Juhu',
    country: 'India',
    rating: 4.97,
    reviewCount: 165,
    experienceYears: 8,
    startingPrice: 310,
    currency: 'USD',
    verified: true,
    featured: true,
    proMember: true,
    responseTimeMinutes: 15,
    minAdvanceBookingDays: 21,
    travelsToVenue: true,
    organicChemicalFreeGuarantee: true,
    badges: ['Top Portrait Specialist', 'Verified Pro', 'Natural Henna Certified'],
    specialties: ['Bridal', 'Rajasthani & Traditional', 'Minimalist Mandala'],
    socialLinks: {
      instagram: 'https://instagram.com',
      whatsapp: '+919820011223',
    },
    stats: {
      completedWeddings: 380,
      bridesServed: 530,
      repeatClientsPercent: 93,
    },
    packages: [
      {
        id: 'ritika-pkg-1',
        artistId: 'artist-ritika-patel',
        title: 'Custom Storytelling Portrait Bridal',
        tier: 'bridal_royal',
        price: 590,
        originalPrice: 680,
        durationMinutes: 260,
        handsDescription: 'Full arms with bride & groom portraits, pet sketch, and proposal skyline.',
        feetIncluded: true,
        organicCones: true,
        touchupKit: true,
        popular: true,
        description: 'Your love story etched in organic Rajasthani henna with bespoke portraits.',
        inclusions: [
          'Full arm bridal coverage past elbows',
          'Detailed hand-drawn portrait of couple & wedding vows',
          'Intricate feet henna to mid-calf',
          'Organic cone kit with lavender-eucalyptus oil blend',
        ],
      },
    ],
    portfolio: [
      {
        id: 'port-rp-1',
        title: 'Couple Portrait & Lotus Garland',
        category: 'Bridal',
        imageUrl: 'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?auto=format&fit=crop&w=800&q=80',
        description: 'Delicate miniature portrait embedded in traditional floral jaal.',
        likesCount: 1720,
        featured: true,
      },
    ],
    reviews: [
      {
        id: 'rev-rp-1',
        artistId: 'artist-ritika-patel',
        customerName: 'Pooja Shah',
        customerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
        customerCity: 'Mumbai',
        rating: 5,
        date: '1 week ago',
        eventType: 'Wedding / Bridal',
        comment: 'Ritika drew our golden retriever puppy into my palm henna and everyone cried happy tears! Outstanding artist.',
        verifiedBride: true,
      },
    ],
    availability: [
      {
        date: '2026-09-08',
        slots: [
          { time: '10:30 AM', available: true },
          { time: '03:30 PM', available: true },
        ],
      },
    ],
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-darkest-stain-secrets',
    slug: 'secrets-to-getting-the-darkest-bridal-mehndi-stain',
    title: 'The Ultimate Guide: 7 Secrets to Getting a Rich Mahogany Bridal Mehndi Stain',
    excerpt: 'Discover the exact science, organic oil blends, clove steaming rituals, and aftercare timelines recommended by top celebrity mehndi artists.',
    content: `Getting that deep, burgundy-to-blackish stain on your wedding day isn’t just luck—it’s an art form guided by temperature, hydration, and organic aftercare. Here are the top rules from certified master artisans:\n\n1. **Say No to Chemical "Black Henna":** Always insist on 100% natural, triple-filtered Rajasthani or Sojat henna. Pure henna takes 24 to 48 hours to peak via natural oxidation.\n2. **The Clove Smoke Ritual:** After scraping (never washing!) the dried paste, gently steam your hands over warm cloves on a dry tawa for 2-3 minutes. The essential eugenol vapor deepens the color pigment.\n3. **Keep Water Away for 24 Hours:** Water stops the oxidation process. Apply pure coconut oil, balms, or mustard oil before showering.\n4. **Seal with Lemon-Sugar or Medical Tape:** A light dab of lemon and sugar keeps the paste moist on your skin longer, allowing lawsone dye molecules to penetrate deeply into epidermal layers.`,
    coverImage: 'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?auto=format&fit=crop&w=800&q=80',
    authorName: 'Ayesha Noor Khan',
    authorRole: 'Master Henna Couturier',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    publishedDate: 'August 24, 2026',
    readTimeMinutes: 6,
    category: 'Care & Staining',
    tags: ['Bridal Care', 'Dark Stain', 'Organic Henna', 'Wedding Checklist'],
  },
  {
    id: 'blog-arabic-vs-rajasthani',
    slug: 'arabic-vs-rajasthani-mehndi-how-to-choose',
    title: 'Arabic vs. Rajasthani Henna: Which Style Complements Your Bridal Aesthetic?',
    excerpt: 'Explore the key visual differences between flowing bold Gulf vines and dense symmetrical Marwari jaal, and how to pair them with your lehenga.',
    content: `Choosing the right mehndi style depends on your wedding outfits, ceremony lighting, and personal vibe.\n\n- **Arabic & Gulf Henna:** Emphasizes negative skin space, high-contrast bold shading, and diagonal floral bel trails. Ideal for pastel lehengas, fusion gowns, and contemporary jewelry.\n- **Rajasthani & Marwari Henna:** Dense, royal, and symmetrical. Filled with intricate jaal (mesh), peacocks, royal palanquins, and customized couple portraits. Perfect for traditional crimson red, velvet maroon, and heavy gold zardozi attire.\n- **Indo-Arabic Fusion:** The best of both worlds, offering bold floral outlines filled with micro-fine Indian gridwork.`,
    coverImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    authorName: 'Priya Sharma',
    authorRole: 'Heritage Rajasthani Artist',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    publishedDate: 'August 18, 2026',
    readTimeMinutes: 5,
    category: 'Styles & Culture',
    tags: ['Style Guide', 'Bridal Inspiration', 'Arabic Henna', 'Rajasthani Mehndi'],
  },
  {
    id: 'blog-bridal-mehendi-timeline',
    slug: 'bridal-mehndi-timeline-planning-your-wedding-week',
    title: 'The Perfect Bridal Mehndi Timeline: When to Book, Apply, and Plan Your Sangeet',
    excerpt: 'Avoid wedding week stress with this exact day-by-day roadmap for manicure, waxing, mehndi application, and photo sessions.',
    content: `Timing your mehndi ceremony is crucial for peak stain depth during your main wedding and reception events.\n\n- **48 Hours Before Wedding Day:** Ideal time for Mehndi application. This allows the full 48 hours for oxidation so the stain reaches maximum dark mahogany depth on your wedding morning.\n- **72 Hours Before:** Complete all waxing, manicures, and body scrubs. Applying henna over freshly exfoliated skin yields the longest-lasting stain.\n- **The Sangeet Night:** Schedule the sangeet either the day after your bridal mehndi or ensure your hands are completed earlier in the afternoon so you can dance without smudging!`,
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    authorName: 'Zainab Mirza',
    authorRole: 'Editorial Bridal Stylist',
    authorAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=200&q=80',
    publishedDate: 'August 10, 2026',
    readTimeMinutes: 4,
    category: 'Bridal Trends',
    tags: ['Wedding Planning', 'Timeline', 'Brides Guide'],
  },
];
